version: '3'        # docker-compose 파일의 버전 명시

services:           # 여러 서비스(컨테이너) 정의 시작
  pickteam-react-app:        # 서비스 이름 (사용자 정의 이름)
    build: .        # 현재 디렉토리의 Dockerfile을 기준으로 이미지 빌드
    container_name: pickteam-react-container  # 생성될 컨테이너의 이름 지정
    #ports:
    #  - "${FRONTEND_PORT}:80"     # 포트번호 (외부포트 3010 -> 컨테이너 내부포트 80으로 설정. nginx와 충돌하지 않도록 하기 위함)
    # 외부에서 포트번호를 통해 이 컨테이너에 직접 접근할 필요 없어짐. 외부 nginx에서 url 기반으로 리버스 프록시해 컨테이너에 직접 접근하므로 불필요한 포트 주석처리
    restart: always # 컨테이너가 중지되면 항상 재시작
    
    networks:
      - pickteam  # 동일한 네트워크에 연결된 다른 컨테이너들과 통신 가능

networks:
  pickteam:
    external: true  # 이미 생성된 외부 네트워크(mynet 등)를 사용. docker network create pickteam 필요
